### PR TITLE
ci: add Nyx-Testing tests

### PR DESCRIPTION
**Pull request by Wenzel**
Add tests based on https://github.com/nyx-fuzz/Nyx-Testing

### CODE REVIEW

**Comment by Wenzel** [comment]
Tests are failing because QEMU-Nyx cannot access KVM-PT

~~~
running 31 tests
test tests::test_create_and_load_pre_snapshot ... FAILED
[QEMU-Nyx] Could not access KVM-PT kernel module!
[QEMU-Nyx] Trying vanilla KVM...
[QEMU-Nyx] Error: NYX requires support for KVM_CAP_DIRTY_LOG_RING in fallback mode!
qemu-system-x86_64: /home/mtarral/_work/kAFL/kAFL/qemu-nyx/accel/kvm/kvm-all.c:2197: kvm_init: Assertion `ret < 0' failed.
~~~

**Comment by Wenzel** [comment]
The runner didn't have a kAFL enabled kernel.
This has been fixed.

Some tests are passing, but the rest are timing out:
~~~
test tests::input_buffer_write_protection_child_32 ... ok
test tests::input_buffer_write_protection_child_64 ... ok
test tests::coverage_bitmap_32 has been running for over 60 seconds
test tests::get_host_configuration_twice_32 has been running for over 60 seconds
test tests::hget_fail_32 has been running for over 60 seconds
test tests::load_root_snapshot_32 has been running for over 60 seconds
test tests::load_root_snapshot_with_custom_input_size_32 has been running for over 60 seconds
test tests::resize_coverage_bitmap_32 has been running for over 60 seconds
test tests::resize_coverage_bitmap_host_to_guest_32 has been running for over 60 seconds
test tests::resize_coverage_bitmap_host_to_guest_fail_32 has been running for over 60 seconds
test tests::resize_small_coverage_bitmap_32 has been running for over 60 seconds
test tests::set_agent_configuration_twice_32 has been running for over 60 seconds
test tests::set_agent_configuration_twice_64 has been running for over 60 seconds
test tests::skip_get_host_configuration_32 has been running for over 60 seconds
test tests::skip_set_agent_configuration_32 has been running for over 60 seconds
~~~

**Comment by schumilo** [comment]
Well, this looks weird. Could be an issue caused by running low on memory since all tests are executed at once (and each test spawns a new VM). 
Try to run the tests sequentially by adding `--test-threads 1` to the command...maybe this will fix the issue.

**Comment by Wenzel** [comment]
I ran a test with `--test-threads 1` on the runner, manually in tmux: 
image
all green ✅ 

However, I don't get the same results in the Github Action job:
image

2 tests are passing ✅ 
And then it hangs for no clear reason until the job max timeout kicks-in (6h).

**Comment by Wenzel** [comment]
Continue to debug the hang issue today.
I started by capturing the [stacktrace](https://gist.github.com/Wenzel/d01536df2990c4d3047de024506c4055) with `rust-gdb`, and noticed that the test was waiting for a [QEMU to write a message on a socket](https://github.com/nyx-fuzz/libnyx/blob/acaf7f6346eeb5f1e2cf043543316909fca43650/fuzz_runner/src/nyx/qemu_process.rs#L58)

Without any further leads, I tried to force cleanup the job workspace because each run (since it's not done automatically on the self-hosted runners).

Apparently it solves the hang issue, not sure exactly why.

**Pull request merged**
